### ISSUE TITLE
Problem building Project - Windows

### ISSUE THREAD

**Issue by Martin-Zander** [vcoda/magma#3]
Hi, i tried to build the project via Visual Studio but i get multiple "identifier not found"-errors in deviceMemoryAllocator.cpp
and "static_assert failed: vertex attribute type not specialized"-errors in vertexInputStructure.inl, did i miss something?

**Comment by vcoda** [comment]
Hi Martin,
I've just cloned a fresh repository and tried to build it with VS 2019 in x86/x64 and Debug/Release configurations.
Every build target compiles/links without issues. Also I use VS 2017 for developement and latest master is also Ok here.
Please make sure that you've cloned repository with --recursive flag. If not, go to magma directory and type "git submodule update --init --recursive". Also make sure that you've installed LunarG Vulkan SDK. If you already did this, tell me about your VS configuration and send the full compilation log.
