### ISSUE TITLE
[Question] Is it possible to init magma from existing Vulkan context?

### ISSUE THREAD

**Issue by trsh** [vcoda/magma#5]
I.e. already having physicalDevice, device and vk instance.

**Comment by vcoda** [comment]
Hi trsh!

Magma has not been designed in this way.
But it's not hard to add this as optional feature. I have created a separate branch for you that implements additional initialization path. Just clone "init_external" branch with "git clone -b init_external https://github.com/vcoda/magma.git" command and use the following methods:

Instance::Instance(VkInstance instance)
Instance::getPhysicalDeviceFromExternalHandle(VkPhysicalDevice physicalDevice)
PhysicalDevice::getDeviceFromExternalHandle(VkDevice device,
    const std::vector<DeviceQueueDescriptor>& queueDescriptors,
    const NullTerminatedStringArray& enabledLayers,
    const NullTerminatedStringArray& enabledExtensions,
    const VkPhysicalDeviceFeatures& enabledFeatures);

You need to provide a list of enabled layers, extension and features along with native handle as other parts of the library may ask device for this info.

Hope this will serve you.

**Comment by trsh** [comment]
Tnx a lot. Will take a look on this in few days
